services:
  # MySQL service
  db:
    image: mysql:8.1
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      - MYSQL_ROOT_PASSWORD=$DATABASE_ROOT_PASSWORD
      - MYSQL_DATABASE=$DATABASE_NAME
      - MYSQL_USER=$DATABASE_USERNAME
      - MYSQL_PASSWORD=$DATABASE_PASSWORD
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - $DATABASE_PORT:$DATABASE_PORT

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    restart: always
    ports:
      - '3001:3001'
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - db

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    restart: always
    ports:
      - 5173:5173
    volumes:
      - ./client:/app
      - /app/node_modules
